name: Build

on:
- push
- workflow_dispatch

env:
  DOCKERHUB_USERNAME: omnibrian
  DOCKERHUB_REPO: podman-exporter

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: docker/setup-qemu-action@v1

    - uses: docker/setup-buildx-action@v1
      id: buildx
      with:
        install: true

    - uses: docker/metadata-action@v3
      id: meta
      with:
        images: ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}

    - uses: docker/login-action@v1
      with:
        username: ${{ env.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - uses: docker/build-push-action@v2
      with:
        context: .
        push: ${{ github.event_name != 'pull_request' }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.output.labels }}
