name: Lint

on:
  push:
    paths:
    - go.sum
    - go.mod
    - "**.go"
    - .github/workflows/lint.yml
    - .golangci.yml
    - Makefile
  pull_request:
    paths:
    - go.sum
    - go.mod
    - "**.go"
    - .github/workflows/lint.yml
    - .golangci.yml
    - Makefile

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: golangci/golangci-lint-action@v2
      with:
        version: v1.44.0
