name: Lint

on:
- push
- pull_request
- workflow_dispatch

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v3
      with:
        go-version: 1.17.x

    - uses: golangci/golangci-lint-action@v3
      with:
        version: v1.44.2
