name: Test

on:
  push:
    paths:
    - go.sum
    - go.mod
    - "**.go"
    - .github/workflows/test.yml
    - Makefile
  pull_request:
    paths:
    - go.sum
    - go.mod
    - "**.go"
    - .github/workflows/test.yml
    - Makefile

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: make test
